project:
  type: website

website:
  title: "Asma Gul's Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
    right:
      - icon: envelope
        href: mailto:asmgu746@student.liu.se
      - icon: file-pdf
        href: assets/CV-AsmaGul-2025.pdf
      - icon: github
        href: https://github.com/guleasma
      - icon: linkedin
        href: https://www.linkedin.com/in/asma-gul-84245013a

  page-footer: 
    left: "Copyright 2025, Asma Gul"
    right: 
      - icon: github
        href: https://github.com/guleasma
      - icon: linkedin
        href: https://www.linkedin.com/in/asma-gul-84245013a

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
